package com.lanyus.typecho.domain;

public class TypechoFieldsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_fields.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_fields.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_fields.cid
     *
     * @return the value of typecho_fields.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_fields.cid
     *
     * @param cid the value for typecho_fields.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_fields.name
     *
     * @return the value of typecho_fields.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_fields.name
     *
     * @param name the value for typecho_fields.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}