package com.lanyus.typecho.domain;

public class TypechoUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.mail
     *
     * @mbggenerated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.screenName
     *
     * @mbggenerated
     */
    private String screenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.created
     *
     * @mbggenerated
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.activated
     *
     * @mbggenerated
     */
    private Integer activated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.logged
     *
     * @mbggenerated
     */
    private Integer logged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.group
     *
     * @mbggenerated
     */
    private String group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_users.authCode
     *
     * @mbggenerated
     */
    private String authcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.uid
     *
     * @return the value of typecho_users.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.uid
     *
     * @param uid the value for typecho_users.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.name
     *
     * @return the value of typecho_users.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.name
     *
     * @param name the value for typecho_users.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.password
     *
     * @return the value of typecho_users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.password
     *
     * @param password the value for typecho_users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.mail
     *
     * @return the value of typecho_users.mail
     *
     * @mbggenerated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.mail
     *
     * @param mail the value for typecho_users.mail
     *
     * @mbggenerated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.url
     *
     * @return the value of typecho_users.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.url
     *
     * @param url the value for typecho_users.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.screenName
     *
     * @return the value of typecho_users.screenName
     *
     * @mbggenerated
     */
    public String getScreenname() {
        return screenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.screenName
     *
     * @param screenname the value for typecho_users.screenName
     *
     * @mbggenerated
     */
    public void setScreenname(String screenname) {
        this.screenname = screenname == null ? null : screenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.created
     *
     * @return the value of typecho_users.created
     *
     * @mbggenerated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.created
     *
     * @param created the value for typecho_users.created
     *
     * @mbggenerated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.activated
     *
     * @return the value of typecho_users.activated
     *
     * @mbggenerated
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.activated
     *
     * @param activated the value for typecho_users.activated
     *
     * @mbggenerated
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.logged
     *
     * @return the value of typecho_users.logged
     *
     * @mbggenerated
     */
    public Integer getLogged() {
        return logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.logged
     *
     * @param logged the value for typecho_users.logged
     *
     * @mbggenerated
     */
    public void setLogged(Integer logged) {
        this.logged = logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.group
     *
     * @return the value of typecho_users.group
     *
     * @mbggenerated
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.group
     *
     * @param group the value for typecho_users.group
     *
     * @mbggenerated
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_users.authCode
     *
     * @return the value of typecho_users.authCode
     *
     * @mbggenerated
     */
    public String getAuthcode() {
        return authcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_users.authCode
     *
     * @param authcode the value for typecho_users.authCode
     *
     * @mbggenerated
     */
    public void setAuthcode(String authcode) {
        this.authcode = authcode == null ? null : authcode.trim();
    }
}