package com.lanyus.typecho.domain;

public class TypechoOptions extends TypechoOptionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_options.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_options.value
     *
     * @return the value of typecho_options.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_options.value
     *
     * @param value the value for typecho_options.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}