package com.lanyus.typecho.domain;

public class TypechoOptionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_options.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_options.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_options.name
     *
     * @return the value of typecho_options.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_options.name
     *
     * @param name the value for typecho_options.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_options.user
     *
     * @return the value of typecho_options.user
     *
     * @mbggenerated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_options.user
     *
     * @param user the value for typecho_options.user
     *
     * @mbggenerated
     */
    public void setUser(Integer user) {
        this.user = user;
    }
}