package com.lanyus.typecho.domain;

public class TypechoContents {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.slug
     *
     * @mbggenerated
     */
    private String slug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.created
     *
     * @mbggenerated
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.modified
     *
     * @mbggenerated
     */
    private Integer modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.authorId
     *
     * @mbggenerated
     */
    private Integer authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.template
     *
     * @mbggenerated
     */
    private String template;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.commentsNum
     *
     * @mbggenerated
     */
    private Integer commentsnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.allowComment
     *
     * @mbggenerated
     */
    private String allowcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.allowPing
     *
     * @mbggenerated
     */
    private String allowping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.allowFeed
     *
     * @mbggenerated
     */
    private String allowfeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.parent
     *
     * @mbggenerated
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_contents.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.cid
     *
     * @return the value of typecho_contents.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.cid
     *
     * @param cid the value for typecho_contents.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.title
     *
     * @return the value of typecho_contents.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.title
     *
     * @param title the value for typecho_contents.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.slug
     *
     * @return the value of typecho_contents.slug
     *
     * @mbggenerated
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.slug
     *
     * @param slug the value for typecho_contents.slug
     *
     * @mbggenerated
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.created
     *
     * @return the value of typecho_contents.created
     *
     * @mbggenerated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.created
     *
     * @param created the value for typecho_contents.created
     *
     * @mbggenerated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.modified
     *
     * @return the value of typecho_contents.modified
     *
     * @mbggenerated
     */
    public Integer getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.modified
     *
     * @param modified the value for typecho_contents.modified
     *
     * @mbggenerated
     */
    public void setModified(Integer modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.order
     *
     * @return the value of typecho_contents.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.order
     *
     * @param order the value for typecho_contents.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.authorId
     *
     * @return the value of typecho_contents.authorId
     *
     * @mbggenerated
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.authorId
     *
     * @param authorid the value for typecho_contents.authorId
     *
     * @mbggenerated
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.template
     *
     * @return the value of typecho_contents.template
     *
     * @mbggenerated
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.template
     *
     * @param template the value for typecho_contents.template
     *
     * @mbggenerated
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.type
     *
     * @return the value of typecho_contents.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.type
     *
     * @param type the value for typecho_contents.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.status
     *
     * @return the value of typecho_contents.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.status
     *
     * @param status the value for typecho_contents.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.password
     *
     * @return the value of typecho_contents.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.password
     *
     * @param password the value for typecho_contents.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.commentsNum
     *
     * @return the value of typecho_contents.commentsNum
     *
     * @mbggenerated
     */
    public Integer getCommentsnum() {
        return commentsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.commentsNum
     *
     * @param commentsnum the value for typecho_contents.commentsNum
     *
     * @mbggenerated
     */
    public void setCommentsnum(Integer commentsnum) {
        this.commentsnum = commentsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.allowComment
     *
     * @return the value of typecho_contents.allowComment
     *
     * @mbggenerated
     */
    public String getAllowcomment() {
        return allowcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.allowComment
     *
     * @param allowcomment the value for typecho_contents.allowComment
     *
     * @mbggenerated
     */
    public void setAllowcomment(String allowcomment) {
        this.allowcomment = allowcomment == null ? null : allowcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.allowPing
     *
     * @return the value of typecho_contents.allowPing
     *
     * @mbggenerated
     */
    public String getAllowping() {
        return allowping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.allowPing
     *
     * @param allowping the value for typecho_contents.allowPing
     *
     * @mbggenerated
     */
    public void setAllowping(String allowping) {
        this.allowping = allowping == null ? null : allowping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.allowFeed
     *
     * @return the value of typecho_contents.allowFeed
     *
     * @mbggenerated
     */
    public String getAllowfeed() {
        return allowfeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.allowFeed
     *
     * @param allowfeed the value for typecho_contents.allowFeed
     *
     * @mbggenerated
     */
    public void setAllowfeed(String allowfeed) {
        this.allowfeed = allowfeed == null ? null : allowfeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.parent
     *
     * @return the value of typecho_contents.parent
     *
     * @mbggenerated
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.parent
     *
     * @param parent the value for typecho_contents.parent
     *
     * @mbggenerated
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_contents.text
     *
     * @return the value of typecho_contents.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_contents.text
     *
     * @param text the value for typecho_contents.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}