package com.lanyus.typecho.domain;

public class TypechoFields extends TypechoFieldsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_fields.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_fields.int_value
     *
     * @mbggenerated
     */
    private Integer intValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_fields.float_value
     *
     * @mbggenerated
     */
    private Float floatValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_fields.str_value
     *
     * @mbggenerated
     */
    private String strValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_fields.type
     *
     * @return the value of typecho_fields.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_fields.type
     *
     * @param type the value for typecho_fields.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_fields.int_value
     *
     * @return the value of typecho_fields.int_value
     *
     * @mbggenerated
     */
    public Integer getIntValue() {
        return intValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_fields.int_value
     *
     * @param intValue the value for typecho_fields.int_value
     *
     * @mbggenerated
     */
    public void setIntValue(Integer intValue) {
        this.intValue = intValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_fields.float_value
     *
     * @return the value of typecho_fields.float_value
     *
     * @mbggenerated
     */
    public Float getFloatValue() {
        return floatValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_fields.float_value
     *
     * @param floatValue the value for typecho_fields.float_value
     *
     * @mbggenerated
     */
    public void setFloatValue(Float floatValue) {
        this.floatValue = floatValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_fields.str_value
     *
     * @return the value of typecho_fields.str_value
     *
     * @mbggenerated
     */
    public String getStrValue() {
        return strValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_fields.str_value
     *
     * @param strValue the value for typecho_fields.str_value
     *
     * @mbggenerated
     */
    public void setStrValue(String strValue) {
        this.strValue = strValue == null ? null : strValue.trim();
    }
}