package com.lanyus.typecho.domain;

public class TypechoRelationshipsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_relationships.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typecho_relationships.mid
     *
     * @mbggenerated
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_relationships.cid
     *
     * @return the value of typecho_relationships.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_relationships.cid
     *
     * @param cid the value for typecho_relationships.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typecho_relationships.mid
     *
     * @return the value of typecho_relationships.mid
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typecho_relationships.mid
     *
     * @param mid the value for typecho_relationships.mid
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}