package com.lanyus.typecho.dao;

import com.lanyus.typecho.domain.TypechoComments;

public interface TypechoCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_comments
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer coid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_comments
     *
     * @mbggenerated
     */
    int insert(TypechoComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_comments
     *
     * @mbggenerated
     */
    int insertSelective(TypechoComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_comments
     *
     * @mbggenerated
     */
    TypechoComments selectByPrimaryKey(Integer coid);
    int countByCid(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TypechoComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TypechoComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TypechoComments record);
}