package com.lanyus.typecho.dao;

import com.lanyus.typecho.domain.TypechoContents;
import com.lanyus.typecho.domain.TypechoRelationshipsKey;

import java.util.List;

public interface TypechoRelationshipsMapper {
    List<TypechoContents> selectByCid(Integer cid);
    List<TypechoContents> selectByMid(Integer mid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_relationships
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TypechoRelationshipsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_relationships
     *
     * @mbggenerated
     */
    int insert(TypechoRelationshipsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typecho_relationships
     *
     * @mbggenerated
     */
    int insertSelective(TypechoRelationshipsKey record);
}